### ISSUE TITLE
How to change logging directory?

### ISSUE THREAD

**Issue by TommasoBendinelli** [navarasu/opencv-log#16]

**Comment by navarasu** [comment]
The option to change logging directory is added in the latest release 1.2.2

`pip install --upgrade opencv-log`

Refer the docs for detail
https://navarasu.github.io/opencv-log/configuration.html#change-log-path

This release mainly adds log rotation for each run,
Now,
 * Log get rotated for each run instead of getting cleared
*  Log folder `log/` directory will not be deleted ( to share space for other services logs)
